---
- name: Restart
  hosts: all
  remote_user: root
  tasks:
    - name: restart...
      shell: "kill `ps -ef | grep filebeat | grep -v grep | awk '{print $2}'`;nohup {{install_dir}}/{{app_name}}/filebeat -e -c {{install_dir}}/{{app_name}}/filebeat.yml > {{install_dir}}/{{app_name}}/filebeat.log  2>&1 &"
      async: 10
      poll: 5

