---
- name: create install directory
  file: path={{ install_dir }} state=directory
- name: create log directory
  file: path={{ log_dir }} state=directory
- name: create data directory
  file: path={{ data_dir }} state=directory
- name: clear install directory
  shell: rm -fr {{ install_dir }}/*
- name: unarchive binary to install directory
  unarchive: src={{ binary_src_dir }}/{{ binary_name }} dest={{ install_dir }}
- name: copy templates to install directory
  template: src=elasticsearch.yml dest={{ install_dir }}/{{app_name}}/config/elasticsearch.yml
- name: set the user to the directory
  shell: chown -R es:es {{ install_dir }} {{log_dir}} {{data_dir}}
