---
- name: Kafka restart
  hosts: all
  remote_user: root
  tasks:
    - name: restart kafka...
      shell: "{{install_dir}}/{{app_name}}/bin/kafka-server-stop.sh;{{install_dir}}/{{app_name}}/bin/kafka-server-start.sh -daemon {{install_dir}}/{{app_name}}/config/server.properties"
